<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "trainingcaces"
 *
 * Auto generated by Extension Builder 2020-06-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Training Caces',
    'description' => 'Training Caces',
    'category' => 'plugin',
    'author' => 'Dmitry Vasilev',
    'author_email' => 'dmitry@t3dev.ru',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
